// Code generated by Prisma CLI (https://github.com/prisma/prisma) and prisma-client-lib@0.2.58. DO NOT EDIT.

import { GraphQLSchema } from "graphql";
import { IResolvers } from "graphql-tools/dist/Interfaces";
import { makePrismaClientClass, BaseClientOptions } from "prisma-client-lib";
import { typeDefs } from "./prisma-schema";

type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U];

export interface Exists {
  segment: (where?: SegmentWhereInput) => Promise<boolean>;
}

export interface Node {}

export interface Fragmentable {
  $fragment<T>(fragment: string | Object): T;
}

export interface Prisma {
  $exists: Exists;
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>;
  $getAbstractResolvers(filterSchema?: GraphQLSchema | string): IResolvers;

  /**
   * Queries
   */

  segment: (where: SegmentWhereUniqueInput) => Segment;
  segments: (
    args?: {
      where?: SegmentWhereInput;
      orderBy?: SegmentOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => Promise<Array<SegmentNode>>;
  segmentsConnection: (
    args?: {
      where?: SegmentWhereInput;
      orderBy?: SegmentOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => SegmentConnection;
  node: (args: { id: ID_Output }) => Node;

  /**
   * Mutations
   */

  createSegment: (data: SegmentCreateInput) => Segment;
  updateSegment: (
    args: { data: SegmentUpdateInput; where: SegmentWhereUniqueInput }
  ) => Segment;
  updateManySegments: (
    args: { data: SegmentUpdateInput; where?: SegmentWhereInput }
  ) => BatchPayload;
  upsertSegment: (
    args: {
      where: SegmentWhereUniqueInput;
      create: SegmentCreateInput;
      update: SegmentUpdateInput;
    }
  ) => Segment;
  deleteSegment: (where: SegmentWhereUniqueInput) => Segment;
  deleteManySegments: (where?: SegmentWhereInput) => BatchPayload;

  /**
   * Subscriptions
   */

  $subscribe: Subscription;
}

export interface Subscription {
  segment: (
    where?: SegmentSubscriptionWhereInput
  ) => SegmentSubscriptionPayloadSubscription;
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T;
}

/**
 * Types
 */

export type SegmentOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "name_ASC"
  | "name_DESC"
  | "videoId_ASC"
  | "videoId_DESC"
  | "startTime_ASC"
  | "startTime_DESC"
  | "endTime_ASC"
  | "endTime_DESC"
  | "mastery_ASC"
  | "mastery_DESC"
  | "category_ASC"
  | "category_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type MutationType = "CREATED" | "UPDATED" | "DELETED";

export interface SegmentCreateInput {
  name: String;
  videoId: String;
  startTime: Int;
  endTime: Int;
  mastery?: Int;
  category?: String;
  tags?: SegmentCreatetagsInput;
}

export interface SegmentCreatetagsInput {
  set?: String[] | String;
}

export interface SegmentWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  videoId?: String;
  videoId_not?: String;
  videoId_in?: String[] | String;
  videoId_not_in?: String[] | String;
  videoId_lt?: String;
  videoId_lte?: String;
  videoId_gt?: String;
  videoId_gte?: String;
  videoId_contains?: String;
  videoId_not_contains?: String;
  videoId_starts_with?: String;
  videoId_not_starts_with?: String;
  videoId_ends_with?: String;
  videoId_not_ends_with?: String;
  startTime?: Int;
  startTime_not?: Int;
  startTime_in?: Int[] | Int;
  startTime_not_in?: Int[] | Int;
  startTime_lt?: Int;
  startTime_lte?: Int;
  startTime_gt?: Int;
  startTime_gte?: Int;
  endTime?: Int;
  endTime_not?: Int;
  endTime_in?: Int[] | Int;
  endTime_not_in?: Int[] | Int;
  endTime_lt?: Int;
  endTime_lte?: Int;
  endTime_gt?: Int;
  endTime_gte?: Int;
  mastery?: Int;
  mastery_not?: Int;
  mastery_in?: Int[] | Int;
  mastery_not_in?: Int[] | Int;
  mastery_lt?: Int;
  mastery_lte?: Int;
  mastery_gt?: Int;
  mastery_gte?: Int;
  category?: String;
  category_not?: String;
  category_in?: String[] | String;
  category_not_in?: String[] | String;
  category_lt?: String;
  category_lte?: String;
  category_gt?: String;
  category_gte?: String;
  category_contains?: String;
  category_not_contains?: String;
  category_starts_with?: String;
  category_not_starts_with?: String;
  category_ends_with?: String;
  category_not_ends_with?: String;
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  updatedAt?: DateTimeInput;
  updatedAt_not?: DateTimeInput;
  updatedAt_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_lt?: DateTimeInput;
  updatedAt_lte?: DateTimeInput;
  updatedAt_gt?: DateTimeInput;
  updatedAt_gte?: DateTimeInput;
  AND?: SegmentWhereInput[] | SegmentWhereInput;
  OR?: SegmentWhereInput[] | SegmentWhereInput;
  NOT?: SegmentWhereInput[] | SegmentWhereInput;
}

export interface SegmentUpdateInput {
  name?: String;
  videoId?: String;
  startTime?: Int;
  endTime?: Int;
  mastery?: Int;
  category?: String;
  tags?: SegmentUpdatetagsInput;
}

export interface SegmentUpdatetagsInput {
  set?: String[] | String;
}

export interface SegmentSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: SegmentWhereInput;
  AND?: SegmentSubscriptionWhereInput[] | SegmentSubscriptionWhereInput;
  OR?: SegmentSubscriptionWhereInput[] | SegmentSubscriptionWhereInput;
  NOT?: SegmentSubscriptionWhereInput[] | SegmentSubscriptionWhereInput;
}

export type SegmentWhereUniqueInput = AtLeastOne<{
  id?: ID_Input;
}>;

export interface NodeNode {
  id: ID_Output;
}

export interface AggregateSegmentNode {
  count: Int;
}

export interface AggregateSegment
  extends Promise<AggregateSegmentNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateSegmentSubscription
  extends Promise<AsyncIterator<AggregateSegmentNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface SegmentPreviousValuesNode {
  id: ID_Output;
  name: String;
  videoId: String;
  startTime: Int;
  endTime: Int;
  mastery?: Int;
  category?: String;
  tags: String[];
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
}

export interface SegmentPreviousValues
  extends Promise<SegmentPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  videoId: () => Promise<String>;
  startTime: () => Promise<Int>;
  endTime: () => Promise<Int>;
  mastery: () => Promise<Int>;
  category: () => Promise<String>;
  tags: () => Promise<String[]>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
}

export interface SegmentPreviousValuesSubscription
  extends Promise<AsyncIterator<SegmentPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  videoId: () => Promise<AsyncIterator<String>>;
  startTime: () => Promise<AsyncIterator<Int>>;
  endTime: () => Promise<AsyncIterator<Int>>;
  mastery: () => Promise<AsyncIterator<Int>>;
  category: () => Promise<AsyncIterator<String>>;
  tags: () => Promise<AsyncIterator<String[]>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
}

export interface SegmentEdgeNode {
  cursor: String;
}

export interface SegmentEdge extends Promise<SegmentEdgeNode>, Fragmentable {
  node: <T = Segment>() => T;
  cursor: () => Promise<String>;
}

export interface SegmentEdgeSubscription
  extends Promise<AsyncIterator<SegmentEdgeNode>>,
    Fragmentable {
  node: <T = SegmentSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface PageInfoNode {
  hasNextPage: Boolean;
  hasPreviousPage: Boolean;
  startCursor?: String;
  endCursor?: String;
}

export interface PageInfo extends Promise<PageInfoNode>, Fragmentable {
  hasNextPage: () => Promise<Boolean>;
  hasPreviousPage: () => Promise<Boolean>;
  startCursor: () => Promise<String>;
  endCursor: () => Promise<String>;
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfoNode>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>;
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>;
  startCursor: () => Promise<AsyncIterator<String>>;
  endCursor: () => Promise<AsyncIterator<String>>;
}

export interface SegmentNode {
  id: ID_Output;
  name: String;
  videoId: String;
  startTime: Int;
  endTime: Int;
  mastery?: Int;
  category?: String;
  tags: String[];
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
}

export interface Segment extends Promise<SegmentNode>, Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  videoId: () => Promise<String>;
  startTime: () => Promise<Int>;
  endTime: () => Promise<Int>;
  mastery: () => Promise<Int>;
  category: () => Promise<String>;
  tags: () => Promise<String[]>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
}

export interface SegmentSubscription
  extends Promise<AsyncIterator<SegmentNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  videoId: () => Promise<AsyncIterator<String>>;
  startTime: () => Promise<AsyncIterator<Int>>;
  endTime: () => Promise<AsyncIterator<Int>>;
  mastery: () => Promise<AsyncIterator<Int>>;
  category: () => Promise<AsyncIterator<String>>;
  tags: () => Promise<AsyncIterator<String[]>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
}

export interface SegmentSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface SegmentSubscriptionPayload
  extends Promise<SegmentSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = Segment>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = SegmentPreviousValues>() => T;
}

export interface SegmentSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<SegmentSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = SegmentSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = SegmentPreviousValuesSubscription>() => T;
}

export interface SegmentConnectionNode {}

export interface SegmentConnection
  extends Promise<SegmentConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = Promise<Array<SegmentEdgeNode>>>() => T;
  aggregate: <T = AggregateSegment>() => T;
}

export interface SegmentConnectionSubscription
  extends Promise<AsyncIterator<SegmentConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<Array<SegmentEdgeSubscription>>>>() => T;
  aggregate: <T = AggregateSegmentSubscription>() => T;
}

export interface BatchPayloadNode {
  count: Long;
}

export interface BatchPayload extends Promise<BatchPayloadNode>, Fragmentable {
  count: () => Promise<Long>;
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayloadNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>;
}

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. 
*/
export type Int = number;

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean;

/*
DateTime scalar input type, allowing Date
*/
export type DateTimeInput = Date | string;

/*
DateTime scalar output type, which is always a string
*/
export type DateTimeOutput = string;

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number;
export type ID_Output = string;

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string;

export type Long = string;

/**
 * Type Defs
 */

export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  endpoint: `${process.env["PRISMA_ENDPOINT"]}`
});
export const prisma = new Prisma();
